---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Config
- type: document
  path: config.json
  label: Site Info
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
